import "./globals.css";
import { Inter } from "next/font/google";
import { cx } from "../utils";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";

// Define the Inter font
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-in",
});

// Define the Manrope font
const Manrope = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mr",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cx(inter.variable, Manrope.variable, "font-mr bg-light")}
      >
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
